name: Run Check
run-name: Run Check on branch ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  check-python:
    name: Check Python
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: true
      - name: Cache Python Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9' # TODO: 3.8?
          cache: pip
          #pip-version:
          pip-install: -r requirements-dev.txt
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2.0.2
        with:
          checkName: 'check-python' # NOTE: this needs to be the same as the job name
          #plugins: flake8-spellcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Test # TODO: need to setup localstack
      #  run: python3 -m unittest discover -v -s test/ -p 'test_*.py'
